# Generated by Django 6.0 on 2026-01-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='items_json',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', "Hisobni to'ldirish"), ('purchase', 'Xarid'), ('refund', 'Pulni qaytarish')], max_length=10),
        ),
    ]
